default: &default
  adapter: postgresql
  encoding: unicode
 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: desafio_espresso_development

test:
  <<: *default
  database: desafio_espresso_test

production:
  <<: *default
  database: desafio_espresso_production
  username: desafio_espresso
  password: <%= ENV["DESAFIO_ESPRESSO_DATABASE_PASSWORD"] %>
